import React from "react";

export default function CountryOptions() {
  return (
    <>
      <option value="afghanistan">Afghanistan</option>
      <option value="albania">Albania</option>
      <option value="algeria">Algeria</option>
      <option value="andorra">Andorra</option>
      <option value="angola">Angola</option>
      <option value="antigua+and+barbuda">Antigua and Barbuda</option>
      <option value="argentina">Argentina</option>
      <option value="armenia">Armenia</option>
      <option value="australia">Australia</option>
      <option value="austria">Austria</option>
      <option value="azerbaijan">Azerbaijan</option>
      <option value="bahamas">Bahamas</option>
      <option value="bahrain">Bahrain</option>
      <option value="bangladesh">Bangladesh</option>
      <option value="barbados">Barbados</option>
      <option value="belarus">Belarus</option>
      <option value="belgium">Belgium</option>
      <option value="belize">Belize</option>
      <option value="benin">Benin</option>
      <option value="bhutan">Bhutan</option>
      <option value="bolivia">Bolivia</option>
      <option value="bosnia+and+herzegovina">Bosnia and Herzegovina</option>
      <option value="botswana">Botswana</option>
      <option value="brazil">Brazil</option>
      <option value="brunei">Brunei</option>
      <option value="bulgaria">Bulgaria</option>
      <option value="burkina+faso">Burkina Faso</option>
      <option value="burundi">Burundi</option>
      <option value="cabo+verde">Cabo Verde</option>
      <option value="cambodia">Cambodia</option>
      <option value="cameroon">Cameroon</option>
      <option value="canada">Canada</option>
      <option value="central+african+republic">Central African Republic</option>
      <option value="chad">Chad</option>
      <option value="chile">Chile</option>
      <option value="china">China</option>
      <option value="colombia">Colombia</option>
      <option value="comoros">Comoros</option>
      <option value="congo">Congo</option>
      <option value="costa+rica">Costa Rica</option>
      <option value="croatia">Croatia</option>
      <option value="cuba">Cuba</option>
      <option value="cyprus">Cyprus</option>
      <option value="czech+republic">Czech Republic</option>
      <option value="germany">Côte d'Ivoire</option>
      <option value="germany">DR Congo</option>
      <option value="germany">Denmark</option>
      <option value="germany">Djibouti</option>
      <option value="germany">Dominica</option>
      <option value="germany">Dominican Republic</option>
      <option value="germany">Ecuador</option>
      <option value="germany">Egypt</option>
      <option value="germany">El Salvador</option>
      <option value="germany">Equatorial Guinea</option>
      <option value="germany">Eritrea</option>
      <option value="germany">Estonia</option>
      <option value="germany">Eswatini</option>
      <option value="germany">Ethiopia</option>
      <option value="germany">Fiji</option>
      <option value="germany">Finland</option>
      <option value="germany">France</option>
      <option value="germany">Gabon</option>
      <option value="germany">Gambia</option>
      <option value="germany">Georgia</option>
      <option value="germany">Germany</option>
      <option value="germany">Ghana</option>
      <option value="germany">Greece</option>
      <option value="germany">Grenada</option>
      <option value="germany">Guatemala</option>
      <option value="germany">Guinea</option>
      <option value="germany">Guinea-Bissau</option>
      <option value="germany">Guyana</option>
      <option value="germany">Haiti</option>
      <option value="germany">Honduras</option>
      <option value="germany">Hungary</option>
      <option value="germany">Icelan</option>
      <option value="germany">India</option>
      <option value="germany">Indonesia</option>
      <option value="germany">Iran</option>
      <option value="germany">Iraq</option>
      <option value="germany">Ireland</option>
      <option value="germany">Israel</option>
      <option value="germany">Italy</option>
      <option value="germany">Jamaica</option>
      <option value="germany">Japan</option>
      <option value="germany">Jordan</option>
      <option value="germany">Kazakhstan</option>
      <option value="germany">Kenya</option>
      <option value="germany">Kiribati</option>
      <option value="germany">Kuwait</option>
      <option value="germany">Kyrgyzstan</option>
      <option value="germany">Laos</option>
      <option value="germany">Latvia</option>
      <option value="germany">Lebanon</option>
      <option value="germany">Lesotho</option>
      <option value="germany">Liberia</option>
      <option value="germany">Libya</option>
      <option value="germany">Liechtenstein</option>
      <option value="germany">Lithuania</option>
      <option value="germany">Luxembourg</option>
      <option value="germany">Madagascar</option>
      <option value="germany">Malawi</option>
      <option value="germany">Malaysia</option>
      <option value="germany">Maldives</option>
      <option value="germany">Mali</option>
      <option value="germany">Malta</option>
      <option value="germany">Marshall Islands</option>
      <option value="germany">Mauritania</option>
      <option value="germany">Mauritius</option>
      <option value="germany">Mexico</option>
      <option value="germany">Micronesia</option>
      <option value="germany">Moldova</option>
      <option value="germany">Monaco</option>
      <option value="germany">Mongolia</option>
      <option value="germany">Montenegro</option>
      <option value="germany">Morocco</option>
      <option value="germany">Mozambique</option>
      <option value="germany">Myanmar</option>
      <option value="germany">Namibia</option>
      <option value="germany">NauruHoly See</option>
      <option value="germany">Nepal</option>
      <option value="germany">Netherlands</option>
      <option value="germany">New Zealand</option>
      <option value="germany">Nicaragua</option>
      <option value="germany">Niger</option>
      <option value="germany">Nigeria</option>
      <option value="germany">North Korea</option>
      <option value="germany">North Macedonia</option>
      <option value="germany">Norway</option>
      <option value="germany">Oman</option>
      <option value="germany">Pakistan</option>
      <option value="germany">Palau</option>
      <option value="germany">Panama</option>
      <option value="germany">Papua New Guinea</option>
      <option value="germany">Paraguay</option>
      <option value="germany">Peru</option>
      <option value="germany">Philippines</option>
      <option value="germany">Poland</option>
      <option value="germany">Portugal</option>
      <option value="germany">Qatar</option>
      <option value="germany">Romania</option>
      <option value="germany">Russia</option>
      <option value="germany">Rwanda</option>
      <option value="germany">Saint Kitts and Nevis</option>
      <option value="germany">Saint Lucia</option>
      <option value="germany">Samoa</option>
      <option value="germany">San Marino</option>
      <option value="germany">Sao Tome and Principe</option>
      <option value="germany">Saudi Arabia</option>
      <option value="germany">Senegal</option>
      <option value="germany">Serbia</option>
      <option value="germany">Seychelles</option>
      <option value="germany">Sierra Leone</option>
      <option value="germany">Singapore</option>
      <option value="germany">Slovakia</option>
      <option value="germany">Slovenia</option>
      <option value="germany">Solomon Islands</option>
      <option value="germany">Somalia</option>
      <option value="germany">South Africa</option>
      <option value="germany">South Korea</option>
      <option value="germany">South Sudan</option>
      <option value="germany">Spain</option>
      <option value="germany">Sri Lanka</option>
      <option value="germany">St Vincent and Grenadines</option>
      <option value="germany">State of Palestine</option>
      <option value="germany">Sudan</option>
      <option value="germany">Suriname</option>
      <option value="germany">Sweden</option>
      <option value="germany">Switzerland</option>
      <option value="germany">Syria</option>
      <option value="germany">Tajikistan</option>
      <option value="germany">Tanzania</option>
      <option value="germany">Thailand</option>
      <option value="germany">Timor-Leste</option>
      <option value="germany">Togo</option>
      <option value="germany">Tonga</option>
      <option value="trinidad+and+tobago">Trinidad and Tobago</option>
      <option value="tunisia">Tunisia</option>
      <option value="turkey">Turkey</option>
      <option value="turmenistan">Turkmenistan</option>
      <option value="uganda">Uganda</option>
      <option value="ukraine">Ukraine</option>
      <option value="united+arab+emirates">United Arab Emirates</option>
      <option value="united+kingdom">United Kingdom</option>
      <option value="united+states">United States</option>
      <option value="uruguay">Uruguay</option>
      <option value="uzbekistan">Uzbekistan</option>
      <option value="vanuatu">Vanuatu</option>
      <option value="venezuela">Venezuela</option>
      <option value="vietnam">Vietnam</option>
      <option value="yemen">Yemen</option>
      <option value="zambia">Zambia</option>
      <option value="zimbabwe">Zimbabwe</option>
    </>
  );
}
